// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://czdxzclliafbxrxblpjt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6ZHh6Y2xsaWFmYnhyeGJscGp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3NTU3NjksImV4cCI6MjA1NzMzMTc2OX0.9ocdGle1NtGPfqKYqp_ER8XLgTLc_ve4okh-6mYZWgU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);